channels:
  - pytorch
  - rapidsai
  - nvidia
  - conda-forge
  - pyg
dependencies:
  - python==3.9.12
  - cudatoolkit==11.6.0
  - cuda-python==11.7.0
  - cudf==22.06.01[build=cuda_11_py39*]
  - cugraph==22.06.01[build=cuda11_py39*]
  - cuml==22.06.01[build=cuda11_py39*]
  - aiobotocore>=2.4.0
  - anndata==0.7.6
  - awscli==1.25.60  # Needed because of https://github.com/Netflix/metaflow/issues/906, but also good to have for bootstrapping Greenfield instances using this environment.yml
  - boto3==1.24.59
  - botocore==1.27.59
  - dask==2022.5.2
  - distributed==2022.5.2
  - h5py==3.7.0[build=*py39*]
  - louvain==0.7.1
  - mlflow==1.19.0
  - numba==0.55.2
  - numpy>=1.18.5
  - pandas<1.3.0
  - protobuf==3.20.1
  - pyg=2.1.0[build=py39_torch_1.12.0_cu116]
  - pytest==6.2.5
  - python-annoy==1.17.0
  - pytorch==1.12.1
  - pyyaml==5.4.1
  - s3fs==2023.1.0
  - scanpy==1.8.2
  - scipy>=1.4.0
  - umap-learn==0.5.2
