name: Test Docker builds with Mamba CLI / conda-libmamba-solver
on:
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - build: cli
        - build: solver
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
      - name: Install conda ${{ matrix.conda }}
        run: ./build.sh install-conda
      - name: Build install-mamba-${{ matrix.build }}
        run: ./build.sh install-mamba-${{ matrix.build }}
      - name: conda list
        run: conda list
      - name: Run env update
        run: ./build.sh env-update ${{ matrix.build }}
