name: Run Docker builds with Mamba CLI vs. conda-libmamba-solver
on:
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - build: mamba-cli
        - build: mamba-solver
    steps:
      - uses: actions/checkout@v3
      - name: Build install-${{ matrix.build }}
        run: docker build -f${{ matrix.build }}.dockerfile -t${{ matrix.build }} .
