name: Run Docker builds with Mamba CLI vs. conda-libmamba-solver
on:
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - build: mamba-cli
        - build: mamba-solver
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Build ${{ matrix.build }} (1 of 3)
        run: docker build -f ${{ matrix.build }}.dockerfile -t ${{ matrix.build }} .
      - name: Build ${{ matrix.build }} (2 of 3)
        run: |
          docker rmi ${{ matrix.build }}
          docker build -f ${{ matrix.build }}.dockerfile -t ${{ matrix.build }} .
      - name: Build ${{ matrix.build }} (3 of 3)
        run: |
          docker rmi
          docker build -f ${{ matrix.build }}.dockerfile -t ${{ matrix.build }} .
