name: Run Docker builds using the conda CLI (with and without conda-libmamba-solver) vs. the mamba CLI
on:
  push:
    branches: [ test ]
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [ conda-libmamba-solver, mamba ]
        job: [ 1, 2, 3, 4, 5 ]
      fail-fast: false
    name: "${{ matrix.build }}, job ${{ matrix.job }}"
    steps:
      - uses: actions/checkout@v3
      - name: "Build ${{ matrix.build }}: job ${{ matrix.job }}, attempt 1 (includes conda/mamba setup)"
        run: docker build -f ${{ matrix.build }}.dockerfile -t ${{ matrix.build }} .
      - name: "Build ${{ matrix.build }}: job ${{ matrix.job }}, attempt 2 (`env update` only)"
        run: |
          docker rmi --no-prune ${{ matrix.build }}
          docker build -f ${{ matrix.build }}.dockerfile -t ${{ matrix.build }} .
      - name: "Build ${{ matrix.build }}: job ${{ matrix.job }}, attempt 3 (`env update` only)"
        run: |
          docker rmi --no-prune ${{ matrix.build }}
          docker build -f ${{ matrix.build }}.dockerfile -t ${{ matrix.build }} .
      - name: "Build ${{ matrix.build }}: job ${{ matrix.job }}, attempt 4 (`env update` only)"
        run: |
          docker rmi --no-prune ${{ matrix.build }}
          docker build -f ${{ matrix.build }}.dockerfile -t ${{ matrix.build }} .
