name: Run Docker builds using the conda CLI (with and without conda-libmamba-solver) vs. the mamba CLI
on:
  push:
    branches: [ test ]
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [ conda, conda-libmamba-solver, mamba ]
      fail-fast: false
    name: ${{ matrix.build }}
    steps:
      - uses: actions/checkout@v3
      - name: "Build ${{ matrix.build }}"
        run: docker build -f ${{ matrix.build }}.dockerfile -t ${{ matrix.build }} .
